### PR TITLE
Print object

### PR DESCRIPTION
**Pull request by Pinkolik**
Hello!
Sometimes you don't have an abiltiy to override toString() method for third-party classes. That's where this method comes in. It uses reflection to print field names and values in json-style format (not actual json). Very useful for debugging. I hope you'll find it fitting in your library.
I also added a repeatString method for StringUtils. The name speaks for itself :)

### CODE REVIEW

**Comment by mariolpantunes** [comment]
Thanks for your contribution.

**Comment by Pinkolik** [comment]
Can you add a hacktober tag please to this issue? :)

**Comment by mariolpantunes** [comment]
Do you mean a label or a git tag?
Either way, both are created.

**Comment by Pinkolik** [comment]
I'm so sorry I mistyped. I meant a hacktoberfest label, not hacktober

**Pull request merged**
